# Generated by Django 4.2.7 on 2023-11-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='video',
            field=models.FileField(default='EE E EEEE.mp4', upload_to='task_videos/'),
        ),
    ]
